import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import AuthProvider from "@/context/AuthProvider";
import { Toaster } from "@/components/ui/toaster"
import Navbar from '@/components/Navbar';
import Footer from "@/components/footer/Footer";
const inter = Inter({ subsets: ["latin"] });
import { ThemeProvider } from "@/components/theme-provider"
import localFont from "next/font/local";

const satoshi = localFont({
  display: 'swap',
  src: '../../public/fonts/satoshi.ttf',
  variable: '--font-satoshi',
});


export const metadata: Metadata = {
  title: "SomeThink",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <AuthProvider>
        <body className={`${satoshi.variable} font-satoshi antialiased`}>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <Navbar />
            {children}
            <Toaster />
            <Footer />
          </ThemeProvider>
        </body>
      </AuthProvider>

    </html>
  );
}
